# Generated by Django 3.0.3 on 2020-03-14 23:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McsaPhysician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('maxShiftLoad', models.IntegerField(default=0)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='McsaShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(help_text='Day of shift start', verbose_name='Day of shift start')),
                ('end_day', models.DateField(help_text='Day of shift end', verbose_name='Day of shift end')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Ending time', verbose_name='Ending time')),
                ('notes', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Textual notes')),
                ('service', models.CharField(default='Inpatient Center', max_length=30)),
                ('physicianOnCall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mcsa.McsaPhysician')),
            ],
        ),
    ]
