# Generated by Django 3.0.3 on 2020-03-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userMonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMonth', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('userYear', models.IntegerField(choices=[(0, '2020'), (1, '2021'), (2, '2022'), (3, '2023'), (4, '2024'), (5, '2025'), (6, '2026'), (7, '2027'), (8, '2028'), (9, '2029'), (10, '2030')], default=0)),
            ],
        ),
    ]
